### ISSUE TITLE
unable to install in sandbox

### ISSUE THREAD

**Issue by blshkv** [vulndb/python-sdk#13]
```
ebuild vulndb-0.1.0.ebuild manifest install 
>>> Creating Manifest for /data/pentoo/pentoo/dev-python/vulndb
 * vulndb-0.1.0.tar.gz BLAKE2B SHA512 size ;-) ...                                                                           [ ok ]
>>> Unpacking source...
>>> Unpacking vulndb-0.1.0.tar.gz to /var/tmp/portage/dev-python/vulndb-0.1.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/vulndb-0.1.0/work
>>> Preparing source in /var/tmp/portage/dev-python/vulndb-0.1.0/work/vulndb-0.1.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/vulndb-0.1.0/work/vulndb-0.1.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/vulndb-0.1.0/work/vulndb-0.1.0 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    'Topic :: Security'
  File "/usr/lib64/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/usr/lib64/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 453, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 866, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1146, in best_match
    return self.obtain(req, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1158, in obtain
    return installer(requirement)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 520, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/var/tmp/portage/dev-python/vulndb-0.1.0/work/vulndb-0.1.0-python2_7/lib/setuptools_git', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

```

**Comment by blshkv** [comment]
ok, so I removed ```setuptools_git``` and the package is installed smoothly.
It is defenetely **not** required to install the content of vulndb/db is per comment in https://github.com/vulndb/python-sdk/blob/master/setup.py#L26.

It is probably a wrong mechanism to keep that db up to date as well since it will be called once during installation only.

**Comment by blshkv** [comment]
you might want to use ```package_data``` instead, see the following bug report where we have fixed the similar issue: https://github.com/mschwager/fierce/issues/25
